syntax = "proto3";

package envoy.extensions.filters.http.cache_custom.v3;

import "udpa/annotations/status.proto";
import "udpa/annotations/versioning.proto";
import "validate/validate.proto";

option java_package = "io.envoyproxy.envoy.extensions.filters.http.cache_custom.v3";
option java_outer_classname = "CacheProto";
option java_multiple_files = true;
option go_package = "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/cache_custom/v3;cache_customv3";
option (udpa.annotations.file_status).package_version_status = ACTIVE;
option (xds.annotations.v3.file_status).work_in_progress = true;

// [#protodoc-title: Cache Custom Filter]
// [#extension: envoy.filters.http.cache_custom]

// Configuration for the ring buffer cache filter.
// [#next-free-field: 4]
message CacheCustom {
  option (udpa.annotations.versioning).previous_message_type =
      "envoy.config.filter.http.cache_custom.v2alpha.CacheCustom";

  // Maximum number of entries in the cache.
  uint32 max_entries = 1 [(validate.rules).uint32 = {gt: 0}];

  // TTL for cached entries in seconds.
  uint32 ttl_seconds = 2 [(validate.rules).uint32 = {gt: 0}];
  
  // Maximum size of each cached response in bytes.
  uint32 max_response_size_bytes = 3 [(validate.rules).uint32 = {gt: 0}];
}