syntax = "proto3";

package envoy.extensions.filters.http.cache_custom.v3;

import "udpa/annotations/status.proto";
import "validate/validate.proto";

option java_package = "io.envoyproxy.envoy.extensions.filters.http.cache_custom.v3";
option java_outer_classname = "CacheProto";
option java_multiple_files = true;
option go_package = "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/cache_custom/v3;cache_customv3";
option (udpa.annotations.file_status).package_version_status = ACTIVE;

// [#protodoc-title: Cache Custom Filter]
// [#extension: envoy.filters.http.cache_custom]

// Configuration for the ring buffer cache filter.
message CacheCustom {
  // Maximum number of entries per host in the cache.
  uint32 max_entries_per_host = 1 [(validate.rules).uint32 = {gt: 0}];

}
